# Generated by Django 2.1.1 on 2018-09-28 12:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2018, 9, 28, 12, 38, 1, 553004), help_text='Required. Format: YYYY-MM-DD'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_city',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='user_country',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default='noreply@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Blog.User'),
        ),
    ]
